name: "Fetch new videos and send them to Telegram"
on:
  schedule:
    - cron: 0 * * * *
  # uncomment these two lines and comment "schedule" to debug on push
#  push:
#  pull_request:
jobs:
  fetch-and-send:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Fetch newly published YouTube videos
        run: npm run youtube
        id: youtube
        env:
          GOOGLE_OAUTH_CREDENTIALS: ${{ secrets.GOOGLE_OAUTH_CREDENTIALS }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
          GOOGLE_OAUTH_CLIENT_REDIRECT_URI: ${{ secrets.GOOGLE_OAUTH_CLIENT_REDIRECT_URI }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Save last fetch date as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: youtube_last_fetch_date
          path: youtube_last_fetch_date
          if-no-files-found: error
      - name: Send messages to Telegram
        run: npm run telegram
        env:
          VIDEOS: ${{ steps.youtube.outputs.videos }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#      - name: Process pinned messages
#        run: npm run watchlater
#        env:
#          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#          GITHUB_TOKEN: ${{ github.token }}
#          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
#          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
#      - name: Save last chat update ID as an artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: telegram_last_update_id
#          path: telegram_last_update_id
#          if-no-files-found: error

